version: '2'
services:
  primary:
    image: mongo:${MONGO_VERSION}
    command: mongod  --noprealloc --smallfiles --replSet ${REPLSET_NAME}
    ports:
      - "27017:27017"
  secondary:
    image: mongo:${MONGO_VERSION}
    command: mongod  --noprealloc --smallfiles --replSet ${REPLSET_NAME}

networks:
  default:
    driver: bridge
