version: '2'
services:
  rs1:
    image: mongo:latest
    command: mongod --noprealloc --smallfiles --replSet rs1

  rs2:
    image: mongo:latest
    command: mongod --noprealloc --smallfiles --replSet rs2

  cfg:
    image: mongo:latest
    command: mongod --noprealloc --smallfiles --configsvr --replSet cfg --port 27017 --dbpath /data/db

networks:
  default:
    driver: bridge
